language: python
sudo: required
python:
  - "2.7"
  - "3.6"
install:
  - git clone https://github.com/radare/radare2.git
  - cd radare2
  - ./sys/install.sh
  - export PYTHONPATH=$PYTHONPATH:$pwd
  - pip install -r requirements.txt
script:
  - py.test
